---
- hosts: all
  become: true
  tasks:

#This example task, zip the file helloworld.txt to helloworld.zip file

  - name: Ansible zip file example
    archive:
     path: /home/ansible/helloworld.txt
     dest: /home/ansible/helloworld.zip
     format: zip

#This example task, zip multiple files to helloworld.zip file.

  - name: Ansible zip multiple files example
  archive:
   path:
    - /home/ansible/helloworld1.txt
    - /home/ansible/helloworld.txt
   dest: /home/ansible/helloworld.zip
   format: zip


#This example task, zip all files in the /home/ansible directory.

  - name: Ansible zip directory example
    archive:
     path:
      - /home/ansible
     dest: /home/ansible/helloworld.zip
     format: zip